language: java
sudo: false
install: true
dist: trusty

after_success:
  - wget https://raw.githubusercontent.com/GoMint/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/GoMint/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

addons:
  sonarcloud:
    organization: "gomint-github"
  artifacts:
    paths:
      - ./proxprox-server/target/Proxprox.jar

jdk:
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'